### PR TITLE
New Hardware Format

### PR DESCRIPTION
**Pull request by mts299**
New hardware format was presented in DAWG on RST's github: https://github.com/SuperDARN/rst/pull/455 

Now presneting it here such that other are aware of the changes and pyDARN from DVWG can test on the changes to ensure releases of the changes between RST, pyDARN, and hdw repo all work toghether.

### CODE REVIEW

**Comment by mts299** [comment]
@egthomas Thank you for the merge, was going to do it but still working on getting pyDARN to accept the new format.

**Comment by ksterne** [comment]
What is the latest status of this PR?  I ran into an issue when testing the release candidate for RST4.7 and was still using the `default/master` branch of this repo.  Is there still some updates to pydarn that need to happen?

**Comment by ecbland** [comment]
> What is the latest status of this PR? I ran into an issue when testing the release candidate for RST4.7 and was still using the `default/master` branch of this repo. Is there still some updates to pydarn that need to happen?

The updates to pydarn have already been done (https://github.com/SuperDARN/pydarn/pull/225)

**Review by egthomas — APPROVED** [review]

**Comment by egthomas** [comment]
> The updates to pydarn have already been done (https://github.com/SuperDARN/pydarn/pull/225)

@ecbland it looks like the updates to pyDARN have been merged but the new release will not be ready until April 18th (https://github.com/SuperDARN/pydarn/pull/253).

Should we aim for a simultaneous release of all 3 packages (ie pyDARN 3.0, RST 4.7, and this pull request)?

**Comment by ecbland** [comment]
> Should we aim for a simultaneous release of all 3 packages (ie pyDARN 3.0, RST 4.7, and this pull request)?

@egthomas Yes that sounds good to me. The pyDARN devs have a meeting today (in 40min) so I'll bring it up then and report back 😄

**Comment by ecbland** [comment]
Following up from the pyDARN developers meeting yesterday: 
- the pyDARN release is ready to go and it's fine to merge this PR
- RST has its own copy of the hardware files, so it's not actually dependent on merging this PR anyway

We noted that pyDARN pulls hardware files from the `master` branch of this repo. Would we like to take this opportunity before the release to rename `master` to `main`? We can then redirect pyDARN to `main` for this release.

**Comment by aburrell** [comment]
>  Would we like to take this opportunity before the release to rename `master` to `main`?

I think that would be a good idea.

**Pull request merged**
